### ISSUE TITLE
C vide

### ISSUE THREAD

**Issue by Tristan971** [maxpr/ADA#1]
Y'a rien encore 👎  ;'(

**Comment by maxpr** [comment]
Tg mdr

Le 27 sept. 2017 11:09, "Tristan Deloche" <notifications@github.com> a
écrit :

**Comment by Tristan971** [comment]
L’issue GitHub est pas fermée though :^)

**Comment by maxpr** [comment]
Mdr T trop con c un repo qu'on a donné au assistant du cours don't put shit
on it please (oui c des glands ils nous demandent de leur fournir un repo
public)

Le 27 sept. 2017 15:17, "Tristan Deloche" <notifications@github.com> a
écrit :

**Comment by Tristan971** [comment]
Supprime ton message précédent par contre c'est en lecture publique ici même si tu réponds par mail. (github -> ADA -> Issues -> Closed -> cette issue -> supprimer)
